---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Config Cisco IPs
  hosts: cisco
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_command_timeout: 300
  tasks:
    # sh vlan
    - name: Cisco IOS Sets IP addresses
      cisco.ios.ios_l3_interfaces:
        config: "{{ l3_interfaces }}"
          state: overridden
      register: _l3_interface
      become: true

    - name: Cisco IOS Debug IPs before
      debug:
        var: _vlan.before

    - name: Cisco IOS Debug IPs command
      debug:
        var: _vlan.commands

    - name: Cisco IOS Debug IPs after
      debug:
        var: _vlan.after

    - name: Save running to startup when modified
      cisco.ios.ios_config:
        save_when: modified
      become: true