---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Config Cisco IPs
  hosts: arista
  gather_facts: false
  vars_files: vars/cmdb.yml
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
    ansible_command_timeout: 300
  tasks:
    # sh vlan
    - name: Arista EOS Config BGP (Survey)
      arista.eos.eos_vlans:
        config: "{{ vlans }}"
        state: overridden
      register: _vlan
      become: yes

    - name: Arista EOS Debug VLANs before
      debug:
        var: _vlan.before

    - name: Arista EOS Debug VLANs command
      debug:
        var: _vlan.commands

    - name: Arista EOS Debug VLAN after
      debug:
        var: _vlan.after
